name: testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Namelesss step
      - run: echo 123

      # Runs a single command using the runners shell
      - name: Run a one-line script
        id: one-line
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        id: multi-line
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "TEST_YML=xpto" >> $GITHUB_OUTPUT

      # Runs an external script using the runners shell
      - name: Run an external script
        id: external
        run: ./bin/script.sh

      # Pick up stuff from other steps
      - name: Show output
        run: |
          echo $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
          echo TEST_YML: ${{steps.multi-line.outputs.TEST_YML}}
          echo TEST_SH: ${{steps.external.outputs.TEST_SH}}
